version: "3.8"

services:
  test:
    build:
      context: .
      target: test
    volumes:
      - "./coverage:/coverage"
    command:
      - go
      - test
      - -cover
      - -coverprofile=/coverage/coverage.out
      - -v
      - ./...
